<?php
	/** @var $this \MvcCore\View */
/** @var $post \App\Models\Post */
?>

<?php if (!$posts): ?>
	<h1><?=$title?></h1>
	<p class="no-posts-message">No posts available.</p>

<?php else: ?>
	<a 
	   class="posts-order-link" 
	   href="<?=$orderLinkValue?>"><?=$orderLinkText?></a>

	<h1><?=$title?></h1>

	<div class="posts">
		<?php foreach ($posts as $post): ?>
			
			<article class="post">
				<i><?=$this->FormatDate($post->Created)?></i>
				<h2><a href="<?=$post->Url();?>"><?=$post->Title?></a></h2>
				<p><?php echo $post->Perex 
				   ? $post->Perex 
				   : $this->Truncate($post->Content, 100);
				?></p>
			</article>

		<?php endforeach ?>
	</div>
<?php endif; ?>